version: '3.4'

services:
  web:
    image: 'teetimedock.azurecr.io/tee-time'
    build: .
    ports:
      - '80:7777'
    links:
      - teetimedb

  teetimedb:
    image: 'teetimedock.azurecr.io/mongo'
    ports:
      - '27017:27017'
