version: '3.4'

services:
  tee-time:
    image: tee-time
    build: .
    ports:
      - '80:7777'
    links:
      - mongo
  mongo:
    container_name: teetimedb
    image: mongo
    ports:
      - '27017:27017'
